use std::sync::Arc;
use std::collections::HashMap; // 👈 NEW IMPORT
use serde_json::json;
use crate::runtime::executor::runner::{NodeRunner, RunnerFuture};
use crate::runtime::graph::node::{NodeType, RuntimeNode};
use crate::runtime::providers::lipsync::LipSyncProvider;

pub struct LipSyncRunner {
    provider: Arc<dyn LipSyncProvider>,
}

impl LipSyncRunner {
    pub fn new(provider: Arc<dyn LipSyncProvider>) -> Self {
        Self { provider }
    }
}

impl NodeRunner for LipSyncRunner {
    fn handles(&self) -> NodeType { NodeType::LipSync }

    fn execute<'a>(&'a self, node: &'a RuntimeNode, context: &'a crate::runtime::context::execution_context::ExecutionContext) -> RunnerFuture<'a> {
        let provider = self.provider.clone();
        
        // Find the audio file generated by the previous Voice node step
        let audio_path = context.workspace_dir.join("step_2_voice.mp3");
        let output_path = context.workspace_dir.join(format!("{}_visemes.json", node.id));

        Box::pin(async move {
            println!("   👄 [LipSyncRunner] Analyzing audio frequencies for mouth movements...");
            
            provider.generate_visemes(audio_path, output_path.clone()).await?;
            
            // 👇 THE FIX: Return a proper HashMap instead of raw JSON
            let mut outputs = HashMap::new();
            outputs.insert("viseme_file".to_string(), json!(output_path.to_string_lossy()));
            
            Ok(outputs)
        })
    }
}